### ISSUE TITLE
Help with löve version

### ISSUE THREAD

**Issue by flamendless** [BentleyBlanks/imguiDock#9]
Hi, this is kinda unrelated but it would help a lot with your input.

This rep[repo](https://github.com/slages/love-imgui/) for löve imgui binding uses this repo for the docking features, however there are problems with it, please see [this](https://github.com/slages/love-imgui/issues/28)

Thanks! 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
Ive managed to fix this.

**Comment by BentleyBlanks** [comment]
Sry, I’m not familiar with your engine.

But it might be a good idea to replace macro into functions or template functions in debug mode. So that u could see what happened in lua stack.

BTW, imgui’s author already done a version of Imgui dock, check that if u need.
